
export default new Map([
["src/content/casestudies/flux.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasestudies%2Fflux.mdx&astroContentModuleFlag=true")],
["src/content/casestudies/launching-apopt.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasestudies%2Flaunching-apopt.mdx&astroContentModuleFlag=true")],
["src/content/casestudies/planetscale-docs-refresh.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasestudies%2Fplanetscale-docs-refresh.mdx&astroContentModuleFlag=true")],
["src/content/casestudies/objects.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasestudies%2Fobjects.mdx&astroContentModuleFlag=true")],
["src/content/casestudies/planetscale.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasestudies%2Fplanetscale.mdx&astroContentModuleFlag=true")],
["src/content/casestudies/launching-dbmon.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcasestudies%2Flaunching-dbmon.mdx&astroContentModuleFlag=true")],
["src/content/product/planetscale.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproduct%2Fplanetscale.mdx&astroContentModuleFlag=true")],
["src/content/product/splunk-o11y-cloud.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproduct%2Fsplunk-o11y-cloud.mdx&astroContentModuleFlag=true")],
["src/content/blog/asparagus-cottage-cheese-sandwich.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fasparagus-cottage-cheese-sandwich.mdx&astroContentModuleFlag=true")],
["src/content/blog/california-breakfast-bowl.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcalifornia-breakfast-bowl.mdx&astroContentModuleFlag=true")],
["src/content/blog/chai.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fchai.mdx&astroContentModuleFlag=true")],
["src/content/blog/feta-sausage-tomato-mustard-sandwich.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffeta-sausage-tomato-mustard-sandwich.mdx&astroContentModuleFlag=true")],
["src/content/blog/dandelion-chicory-chai.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdandelion-chicory-chai.mdx&astroContentModuleFlag=true")],
["src/content/blog/mango-lassi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmango-lassi.mdx&astroContentModuleFlag=true")],
["src/content/blog/potato-chip-sandwich.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpotato-chip-sandwich.mdx&astroContentModuleFlag=true")],
["src/content/blog/palak-paneer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpalak-paneer.mdx&astroContentModuleFlag=true")],
["src/content/blog/yogurt-dip.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fyogurt-dip.mdx&astroContentModuleFlag=true")]]);
		