image: node:4.2.2

before_script:
  - npm install -g harp

pages:
  cache:
    paths:
    - node_modules

  script:
  - cp node_modules/tachyons/css/tachyons.min.css ./public/css && mv ./public ./public-src harp compile ./public-src public
  artifacts:
    paths:
    - public
  only:
  - master
