image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules

  script:
  - npm install -g harp
  - cp node_modules/tachyons/css/tachyons.min.css ./src/css && harp compile ./src public
  artifacts:
    paths:
    - public
  only:
  - master
